### ISSUE TITLE
New feature suggestion

### ISSUE THREAD

**Issue by jarodium** [trippo/ResponsiveFilemanager#149]
Hello @trippo
I would like to be able to choose only folders, so a mode where you can work only with folders would be great.

**Comment by not-a-lot** [comment]
Hello,
I have the same need : to be able to select a folder already present on the server and return the path to it (which I would put in an <input> element)

**Comment by trippo** [comment]
I can do this adding a function in context menu

**Comment by not-a-lot** [comment]
This would be great ! Something like what you already have on your demo page, but for folders ("Select only folders"). The problem is that currently, a single click opens a folder. So this folder only mode either needs to be a little different, or you could put the option to select the folder in the context menu just as you suggested. I see you already have "Show URL" in the menu. It seems simpler and I don't know what jarodium wants, but for me it would be fine. 

Thanks for your fast reply anyway. Yesterday I had a look at your code, but by the time I understand how to do the change, it could be a while... That's why I was thinking of developping my own file browser with the bare minimum features needed instead :p

**Comment by cisco90** [comment]
Any news or proof of code?

**Comment by trippo** [comment]
sorry i work to integrate ckeditor next release i'll add this functionallity

**Comment by trippo** [comment]
Responsive filemanager 9.9.2 include this feature :)
