### ISSUE TITLE
custom config.php now incompatible

### ISSUE THREAD

**Issue by donShakespeare** [trippo/ResponsiveFilemanager#176]
Great update...but the 9.9.2 update changed a lot of the style of variables.
How do we include custom config in the user folders?

<?php
'MaxSizeUpload' => 1000,
'show_folder_size' => true,
'show_sorting_bar' => true,
'transliteration'  => true,
'image_max_width'  => 970,
'image_max_height' => 500,
'ellipsis_title_after_first_row' => true,
'delete_files' => true,
?>

**Comment by trippo** [comment]
i think you can set in this mode :
```
$config['MaxSizeUpload'] = 1000;
$config['show_folder_size'] = true;
...
```

**Comment by donShakespeare** [comment]
I tried that, it did not work.
This worked:
$MaxSizeUpload = 1000;
$show_folder_size = true;

But it seems variables with arrays get overridden by the main config.php especially for the important allowed extensions

This does not work
$config['ext_file'] = array( 'jpg', 'jpeg', 'png', 'gif' );

nor

$ext_file = array( 'jpg', 'jpeg', 'png', 'gif' );

This is very important. I am still trying to figure it out, thanks @trippo

**Comment by trippo** [comment]
you are right because the script convert array to variable at the beginning of dialog.php so there is 2 possibilities:
- you use variable liìke your example
- move the code that include the sub config.php before extract($config, EXTR_OVERWRITE); on dialog.php -> so you can use array mode.

I will fix this in new version

**Comment by donShakespeare** [comment]
Was the fix this format?
$show_folder_size = true;
