### ISSUE TITLE
Wrong paths returned from TinyMCE 4.1.7

### ISSUE THREAD

**Issue by phpMagpie** [trippo/ResponsiveFilemanager#217]
I have this working perfectly with TinyMCE 4.1.3, but when I upgrade to TinyMCE 4.1.7 returned paths from the plugin look like: 
http://domain.co.uk/current/action/path//uploads/test/paul%20(1).jpg

When they should be: 
/uploads/test/paul%20(1).jpg

Any ideas what could be going wrong?

**Comment by chiendv** [comment]
Make some change in TinyMce 
```javascript
tinyMCE.init({
	 //...
	 document_base_url: window.location.protocol + '//' + window.location.host+'/',
	 relative_urls: true,
	 //convert_urls: false,
	 remove_script_host: true,
     //...
});
```

Hope this help!

**Comment by louisl** [comment]
I had a similar problem.

For some reason the minified plugin.min.js wasn't working.

I replaced plugin.min.js with the raw version: https://github.com/trippo/ResponsiveFilemanager/blob/master/resources/assets/js/plugin.js

My tinyMCE config is:
```
//...
convert_urls: false,
relative_urls: false,
remove_script_host: true,
document_base_url: window.location.protocol + '//' + window.location.host + '/',
//...
```

I needed to use `convert urls:false` otherwise normal urls on a https site would become https://http://www.example.com

(Thanks to @chiendv for the config example.)
