### ISSUE TITLE
TinyMCE 5 RC1 and RESPONSIVE filemanager 

### ISSUE THREAD

**Issue by cfconsultancy** [trippo/ResponsiveFilemanager#531]
In TinyMCE 5 RC1  the RESPONSIVE filemanager isn't working anymore.
Looks like external_plugins has a different behaviour now.

Have you already looked at TinyMCE 5 RC1 ?

**Comment by gordon-matt** [comment]
+ 1

I am using TinyMCE 5.0.3 in some of my projects now and RFM no longer works. An error message in the console is as follows:

`Failed to initialize plugin: responsivefilemanager Error: "editor.addButton has been removed in tinymce 5x, use editor.ui.registry.addButton or editor.ui.registry.addToggleButton or editor.ui.registry.addSplitButton instead"`

**Comment by gordon-matt** [comment]
I think I have solved this by simply modifying the **plugin.js** as follows:

1. Change `addButton('responsivefilemanager', {` to `editor.ui.registry.addButton('responsivefilemanager', {`

2. Change `addMenuItem('responsivefilemanager', {` to `editor.ui.registry.addMenuItem('responsivefilemanager', {`

3. Change `onclick` in both of those to `onAction`

I am not yet able to test it because I have other errors with another TinyMCE plugin of mine that I need to solve.. but I'm pretty sure that should do it. I will update this post once I have had time to actually test it.

**Comment by cfconsultancy** [comment]
That won't work because the use of an url include is not supported anymore by tinymce 5 https://github.com/tinymce/tinymce/issues/4786

**Comment by studiowena** [comment]
we have to w8 for an update...

**Comment by gordon-matt** [comment]
> 
> 
> That won't work because the use of an url include is not supported anymore by tinymce 5 [tinymce/tinymce#4786](https://github.com/tinymce/tinymce/issues/4786)

You're right; I just got around to testing it now and that wasn't enough.

@trippo Any chance we can get a new version of this soon?

**Comment by martyf** [comment]
This will be resolved in a soon-to-be released version of Tiny 5.

**Comment by gordon-matt** [comment]
@mklkj  Very nice work with that PR.. and I can see it working with a new button on the toolbar. However, what about the "Insert/Edit Image" dialog? The one when you click the "Insert" menu and then choose "Image". This is unfortunately not showing a button to choose an image from RFM. Is it still possible to do this in TinyMCE version 5?

**Comment by trippo** [comment]
yes I'm working on
