### ISSUE TITLE
Thumbnail folder and thumbs

### ISSUE THREAD

**Issue by SEModer** [trippo/ResponsiveFilemanager#552]
Hi all.
When I upload an image to the server, "root/upload_dir/thumbnail/" folder  is automatically created and add thumbs. Where can I turn it off or change the path?
In folder root/thumbs thumb files are also created

**Comment by ok-design** [comment]
In UploadHandler.php comment line 169-186 'thumbnail => array'-block the same way as 'medium'-block (line 164-167)

**Comment by trippo** [comment]
You can change this simply edit config.php file

**Comment by SEModer** [comment]
when you see it on config.php?

**Comment by ok-design** [comment]
This doesn’t happen because of the settings in config.php. I don’t use the thumbnail settings (set to valse) and I stil got the folder ‘thumbnail’ in the root of the upload-folder.

**Comment by trippo** [comment]
The thumbnail generation are necessary for the filemanager to work

**Comment by ok-design** [comment]
The thumbnails for the filemanager are created in a folder outside of the folder where the images are uploaded (as set in the configuratie.php). The thumbnail folder from this issue is an extra folder that is created inside the images folder and this extra folder is not configured in config.php

Bij commenting the lines in the uploadHandler this issue disappears.

**Comment by trippo** [comment]
Oh ok you are right I'll fix in next version, thanks
