### ISSUE TITLE
Files is not going to upload which are more than 2 mb

### ISSUE THREAD

**Issue by fuzonmedia** [trippo/ResponsiveFilemanager#62]
Hi 
I did a setup the ResponsiveFilemanager into my webserver located http://filesystem.fuzonmedia.com/ResponsiveFilemanager-master/filemanager/dialog.php . 

The upload features is working fine for file size less than 2mb but not more than 2mb those it is showing a green check after upload . I am using basic upload method . I did not altered the $MaxSizeUpload=100; //Mb variable value . 

Can you please guide me why it is not working for me ? any idea ? 

Thanks 
Nil

**Comment by timmetj** [comment]
Hello,

is it maybe possible to simply add an error during the upload?
Because now the uploader shows the file is uploaded, while it is not, and you can also click the image to insert it, but then the url path is filled with a php error code:
Warning: chmod(): No such file or directory in ../filemanager/upload.php on line 87

Thanks
