### ISSUE TITLE
Adding new functionalities. Got any ideas?

### ISSUE THREAD

**Issue by Mikeyhun** [trippo/ResponsiveFilemanager#67]
Hi there people.

I'm planning to add new functionalities to this great file manager.

Next update:
- More bugfix
- Update to bootstrap 3 (and all components)

Might push out:
- Figure out a new way of storing lang. vars in the runtime rather than in hidden fields
- Custom upload options (when uploading files make a new tab where you could specify custom options for the upload session like custom image sizing, thumb creation etc.)

Distant future:
- Multiple file selection/operation
- Directory tree view (for fast navigation)

Done: 
- cut/copy/paste
- drag&drop files/folders
- code cleanup
- modify $_SESSION so there will be no conflicts when used in big projects
- more feedback in a few places
- custom upload sprites for every lang.
- File permissions
- Change language dynamically
- edit/create/view text based files

If you have any more idea or you think something is missing from RF just post a comment here and will try to include it.

**Comment by webtweakers** [comment]
Pity there doesn't seem to be progress on this. I would also be interested in a clearer separation and concise API in order to port this to Python. Angular might be a good idea, indeed.

I've been looking around and imho Responsive Filermanager is one of the better file managers out there. Its only drawback is that it's completely bound to PHP and - at the moment - hard to separate.
